#!/bin/bash

WATCH_PATH="/data/photoframe/images_usb"

PROG=/usr/bin/usb_share.py

test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

mkdir -p ${WATCH_PATH}

start() {
  msg_begin "Starting usb_share"
  ${PROG} > /dev/null &

  test $? == 0 && msg_done || msg_fail
}

stop() {
  msg_begin "Stopping usb_share"
  killall -q $(basename ${PROG})
  test $? == 0 && msg_done || msg_fail
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

