#!/bin/bash

PATH="/data/photoframe/piusb.bin"

create_piusb() {
    if [ ! -f $PATH ]; then
        echo "Creating piusb.bin"
        /bin/dd bs=1M if=/dev/zero of=$PATH count=4096
        /sbin/mkdosfs $PATH -F 32 -I
    else
        echo "piusb.bin already created"
    fi
}

case "$1" in
    start)
        create_piusb
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
